_BASE_: ../base.yaml
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 172
    TRAIN_CLASS_JSON: "datasets/coco.json"
    # TEST_CLASS_JSON: "datasets/indraeye.json"
    TEST_CLASS_JSON: "datasets/coco.json"
DATASETS:
  TRAIN: ("coco_2017_train_stuff_all_sem_seg",)
  TEST: ("coco_2017_val_stuff_all_sem_seg",)
  # TEST: ("IE_Segmentation_sem_seg_val",)
  # TEST: ("msrs_rgb_sem_seg_val",)
SOLVER:
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 5000

