_BASE_: ../base.yaml
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 9
    TRAIN_CLASS_JSON: "datasets/openearth.json"
    TEST_CLASS_JSON: "datasets/openearth.json"
DATASETS:
  TRAIN: ("openearth_sem_seg_train_rgb",)
  TEST: ("openearth_sem_seg_test_rgb",)
SOLVER:
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 20000


