_BASE_: ../../base.yaml
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 12
    TRAIN_CLASS_JSON: "datasets/cart_rgb.json"
    TEST_CLASS_JSON: "datasets/cart_rgb.json"
DATASETS:
  TRAIN: ("carti_sem_seg_train",)
  TEST: ("carti_sem_seg_val",)
SOLVER:
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 20000


