_BASE_: ../../base.yaml
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 13
    TRAIN_CLASS_JSON: "datasets/indraeye_ir.json" # just contains classes
    TEST_CLASS_JSON: "datasets/indraeye_ir.json"
DATASETS:
  TRAIN: ("IE_Segmentation_rgb_sem_seg_train",)
  TEST: ("IE_Segmentation_rgb_sem_seg_val",)
SOLVER:
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 5000
