_BASE_: ../../base.yaml
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 13
    TRAIN_CLASS_JSON: "datasets/indraeye_ir.json"
    TEST_CLASS_JSON: "datasets/indraeye_ir.json"
DATASETS:
  TRAIN: ("IE_Segmentation_sem_seg_train",)
  TEST: ("IE_Segmentation_sem_seg_val",) # since registration name is val, tho test directory is being used (register_indraeye_ir.py)
SOLVER:
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 5000
